### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by stephyspiccoli** [Christephim/web-app#11]

**Comment by DoctorDiLauro** [comment]
![wireframes l](https://user-images.githubusercontent.com/16653166/35875955-dd114264-0b3e-11e8-9fad-a89354c15005.jpg)
![wireframes xs](https://user-images.githubusercontent.com/16653166/35875956-dd1c2b48-0b3e-11e8-97ce-a96f526a0057.jpg)
