### ISSUE TITLE
Name & Logo

### ISSUE THREAD

**Issue by DoctorDiLauro** [Christephim/web-app#12]

**Comment by KevinBMcIntyre** [comment]
![revelent app icon](https://user-images.githubusercontent.com/10464597/35936240-aaa32036-0c10-11e8-82b9-848fa6356eb6.png)

**Comment by KevinBMcIntyre** [comment]
![revelent app icon v2-09](https://user-images.githubusercontent.com/10464597/36009926-a73be326-0d1c-11e8-9040-3e1efa8c04b9.png)
