### ISSUE TITLE
Sprint 3 Review

### ISSUE THREAD

**Issue by stephyspiccoli** [Christephim/web-app#15]

**Comment by DoctorDiLauro** [comment]
This Sprint was successful in that the rest of the Web UX tasks were completed. I believe that it could have been more successful if certain aspects were completed in the previous task, allowing a more fleshed out prototype. Even with that being said, I believe the prototype that was created is a good representation of our goal.

**Comment by KevinBMcIntyre** [comment]
This week went well, we found an amazing punny name Relevant (Real Events) that I am very happy with. I now have a firm belief that this project will be as professional as the name. Things that could have gone better is perhaps communication between name and colours. It was a challenge to get it done on time but we did it, and for that I am happy with my team.

**Comment by stephyspiccoli** [comment]
This week we had to complete the prototype, name, logo, and visual design of our app. The prototype created was pretty successful and we were able to come up with a name and a logo for our app. Overall we communicated well to complete the tasks.

**Comment by DoctorDiLauro** [comment]
@thomasjbradley
