### ISSUE TITLE
Pre-code analysis

### ISSUE THREAD

**Issue by DoctorDiLauro** [Christephim/web-app#16]
Analyze Wireframe to break it into bits of code. Plan before execution.

**Comment by stephyspiccoli** [comment]
This past week we didn't do much related to our app design. We were a bit relaxed and turned our attention to other projects and classes. But we will pick up for this coming week and we will be starting our code.

**Comment by KevinBMcIntyre** [comment]
We had a very easy week in terms of the focus on the app itself. We felt that we were so ahead we were able to focus our energy on other projects. This coming week we will start working on our code.

**Comment by DoctorDiLauro** [comment]
This past week I spent more time focusing on other classes and projects, therefore not much was completed in the coding department. Looking back I could have at done a little more preparation for coding, but this coming week I will be more on top of coding.

**Comment by DoctorDiLauro** [comment]
@thomasjbradley
