### ISSUE TITLE
Website Goals

### ISSUE THREAD

**Issue by KevinBMcIntyre** [Christephim/web-app#4]
Develop website goals

**Comment by DoctorDiLauro** [comment]
Local arts and culture is vibrant, abundant, and extremely important, but it can be difficult to hear about all the events that interest you before it's too late. Our app will allow individuals to find events that are relevant to their interests easier and faster, and keep track of what they have already planned to attend. Our app is an area based event browser and manager that is tailored to be as personal as the user's taste.
