### ISSUE TITLE
UX Rubric

### ISSUE THREAD

**Issue by KevinBMcIntyre** [Christephim/web-app#7]
Establish a rubric for the course

**Comment by DoctorDiLauro** [comment]
Changed description to UX Rubric

**Comment by stephyspiccoli** [comment]
| |0 points | 1 point | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Research** | None to little research done | Some research done but not extensive | More research done but not fully complete | Good research, competitive analysis, target audience and website goals |
| **Teamwork** | No communication, and no organization as a team | Some communication but no organization within completing tasks | Individual tasks were completed but lacked communication with other team mates | Team communicated well, were able to help other as well as completing each individual tasks |
| **Design** | Barely started, grey boxes, no content | Missing lots of pages & images, some content added | Contain pages and images, but images are low quality, some content missing | Pages added with good quality pictures and all original content|
| **Prototyping** | Low to none wireframe fidelity | Some wireframe done but low to medium quality | Good wireframes | High quality wireframes |
| **Easy to use** | App is not functional at all | App is somewhat functional but pages don't connect to each other | App is function but could use some improving | App is easy to use and self |explanatory |

**Comment by DoctorDiLauro** [comment]
Research: 3/3
All aspects of the research were completed

Teamwork: 3/3
Communication maintained, tasks delegated evenly, help was given when needed

Design: 2/3
Pages were present, with real event content (taken from Facebook), could've used some images/colour

Wireframes: 2.5/3
Paper wireframes done with considerable detail, XD wireframe was well made but could've been more detailed

Easy to Use: 2/3
App is functional, pages and buttons are connected, but improvements to functionality are needed
